### ISSUE TITLE
User API

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/core#15]

**Comment by mostafabarmshory** [comment]
این کار رو لازم داریم. می‌خوای خودم انجامش بدم؟

**Comment by hadimansouri** [comment]
یکی از مشکلاتی که بهش برخوردم برای به‌روزرسانی کاربرهاست.
یک کلاس دیگه اضافه کردم که بشه به صورت پویا یه فرم برای به‌روزرسانی مدل‌های مختلف ایجاد کرد (از روی ویژگی editable)
مشکلی که وجود داره اینه که وقتی به روزرسانی می‌خواد انجام بشه فیلدهایی که نوعشون بولی هست وقتی کاربر براشون مقدار نکرده باشه مقدارشون می‌شه false که تو این حالت هم حتی با متد clean نمی‌شه تشخیص داد که این مقدار رو کاربر ست کرده یا اینکه به دلیل تعیین نشدن مقدار. 
به همین دلیل وقتی user رو به روز می‌کنی تمام فیلدهای بولی که براش مقدار تعیین نشده false می شن
مثل adimistrator, staff, active

**Comment by hadimansouri** [comment]
من این کار روش رو فعلا در نظر گرفتم:
فیلدهای بولی مثل administrator, active, staff رو در مدل داده‌ای کاربر قرار می‌دم editable->false
برای تغییر این فیلدها باید از api های دیگری غیر از به روزرسانی اطلاعات کاربر استفاده بشه.

احتمالا برای اکثر مواقع این روش قابل استفاده است

**Comment by hadimansouri** [comment]
تکمیل و تست شد. البته به جز resource های مربوط به message

**Comment by mostafabarmshory** [comment]
مشکلی داشته که دوباره بازش کردی؟
