### ISSUE TITLE
ارتقا ماژول SaaSNewspapre

### ISSUE THREAD

**Issue by hadimansouri** [pluf/core#25]
ماژول saasnewspaper رو توی سرور بهبود بدیم تا بشه برای گزینه‌هایی مثل رویدادها، اخبار و ... توی سایت‌های مختلف ازش استفاده کرد
مثلا موجودیتی با خصوصیات زیر اضافه کنیم: (موجودیت News)
- title
- thumbnail
- content
- author
- creation_date

توی ماژول saasnewspaper باید سیستم category و tag رو هم اضافه کنیم تا بشه اخبار رو دسته‌بندی کرد

**Comment by mostafabarmshory** [comment]
این کار از حوزه این پروژه خارج هست. با روش‌های دیگه مثل ویجت‌های وبرگر حلش کنیم بهتر هست. این ماژول کلا از سیستم حذف می‌شه.
