### ISSUE TITLE
Recomputing expiration date of links base on activation date

### ISSUE THREAD

**Issue by hadimansouri** [pluf/core#31]
Currently expiration date of links in SDP is computed base on creation date (for example one day after creation). I believe that expiration date should be recomputed base on activation date. This means when link is activated, its expiration date should be recomputed again.

Note: If a link has been expired before that is activated, it should not be activated anyway. Also if a link is activated it should not be activated again.

**Comment by MahdiIsComing** [comment]
This issue was solved.
For links associated to priceless assets, expiry date will be applied immediately.
However, for links which are required to be activated, expiry time would be calculated based on activation time.

Thanks for your scrutinizing carefulness.

**Comment by hadimansouri** [comment]
Thanks brother!
How much time for expiry date is considered?
