### ISSUE TITLE
Handle Pluf_model in view

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/core#41]
View has to return an HTTP response.

Pluf_Model is the most return value of a view.

Handle Objects if a view return directly.

**Comment by mostafabarmshory** [comment]
All files must be store related to the tenant storage path. It is essential to backup files.

**Comment by hadimansouri** [comment]
Last statement is not clear! Please give us some details.

**Comment by mostafabarmshory** [comment]
In the current state, views must return an instance of PLuf_HTTP_Response. Most of the time the result is an object and views return a Pluf_HTTP_Response_Json.

Pluf core must handle Pluf_Model if a view returns an object directly.

**Comment by mostafabarmshory** [comment]
Finally, just return an object. The result will be encoded based on user request.
