### ISSUE TITLE
Sdp link failed

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/core#51]
After update (from mahdi) link creation failed:

error message

    {
        "code": 4000,
        "status": 400,
        "link": null,
        "message": "Incorrect datetime value: '' for column 'expiry' at row 1",
        "data": null
    }

and the url is:

    http://localhost:8081/api/sdp/asset/1/link

**Comment by hadimansouri** [comment]
Mahdi was changed code to active links after payment. He does not take it to account that an asset may be free.
