### ISSUE TITLE
Why 'submitter' field is removed from CMS_Content?

### ISSUE THREAD

**Issue by hadimansouri** [pluf/core#52]
@mostafabarmshory 
Why you remove 'submitter' field from CMS_Content?
You should not remove any field with no reasonable reason (even that is extra from point of your view)!

**Comment by hadimansouri** [comment]
@mostafabarmshory 
I add 'submitter' field to CMS_Content again. If you have some reason against it call me!

**Comment by mostafabarmshory** [comment]
Audit log is much more better than using fixed fields. For example:

    user#1 submit content#i on date#k
    user#2 edit      contetn#i on date#k_2

So, it is clear who submit and who change.

**Comment by mostafabarmshory** [comment]
Would you move this issue to cms module, please?

**Comment by hadimansouri** [comment]
This issue should be removed. It is not valid now
