### ISSUE TITLE
Adding authorized permission for new user

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/core#81]
If a new user is created, then authorized permission must be added for current tenant automatically.

**Comment by hadimansouri** [comment]
I add some code for this issue in User_Views_User.
Code is added in create function. It adds authorized permission to each new created user.
In mentioned code I assume that authorized permission has id 3. Also I do not check that server uses rowpermission or not.

**Comment by mostafabarmshory** [comment]
First of all: you can get a permission by its code name

    $perm = Pluf_Permission::getFromString('Pluf.authorized);

Just use row permission. Other case will be removed from core.

**Comment by hadimansouri** [comment]
I edit codes by mentioned note by @mostafabarmshory
