### ISSUE TITLE
Association tables should field 'tenant' in multitenant state

### ISSUE THREAD

**Issue by hadimansouri** [pluf/core#85]
If Pluf is installed in multitenant state all association tables should have field 'tenant'. For example following tables has not such field in mutlitenant state:

- pluf_group_pluf_permission_assoc
- pluf_group_pluf_user_assoc
- pluf_permission_pluf_user_assoc

**Comment by mostafabarmshory** [comment]
Two side of association must be located in a tenant so there is no need adding tenant id in association.

In the other word an association is internal (in tenant) object and managed automatically.
